# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'check24-Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for check24-Task

  pod 'Kingfisher'

end
